Authenticate with es
Aconex/scrutineer pull request #47
Opened 2020-10-30 03:44 UTC by rock-yu

## Proposed changes

Add command-line options to provide credentials when using secured ES 

**This addresses issue #x**

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/Aconex/scrutineer/blob/master/CONTRIBUTING.md) doc
- [x] All tests pass locally with my changes
- [x] I've added unit tests and integration tests.
- [ ] I've added necessary documentation (if appropriate)

## Further comments

2020-10-30 05:35 UTC, tallpsmith requested changes
Looks pretty good!

2020-10-30 05:35 UTC, tallpsmith commented on src/main/java/com/aconex/scrutineer/CmdLineOptionsSSLVerificationModeValidator.java
> +            throw new ParameterException("SSL verification mode can be one of: " + Arrays.toString(sslVerificationModes));
always good to pass back what was received that is invalid. something like:
```
..."Invalid SSL Verification mode '%s' - can be one of: %s", value, Arrays.toString(sslVerificationModes) ...
```

2020-10-30 05:35 UTC, tallpsmith commented on src/main/java/com/aconex/scrutineer/ScrutineerCommandLineOptions.java
> +            description = "Transport client SSL verification mode, accepted values: [none, certificate, full]", validateValueWith = CmdLineOptionsSSLVerificationModeValidator.class)
Do we need to outline in the `description` that the default value is `certificate` ?

2020-10-30 05:35 UTC, tallpsmith commented on src/main/java/com/aconex/scrutineer/ScrutineerCommandLineOptions.java
> +            description = "Transport client SSL verification mode, accepted values: [none, certificate, full]", validateValueWith = CmdLineOptionsSSLVerificationModeValidator.class)
or does the JCommander stuff do that for us (I forgot! )

2020-10-30 05:35 UTC, tallpsmith commented on src/main/java/com/aconex/scrutineer/elasticsearch/ElasticSearchTransportClientFactory.java
> +        LogUtils.debug(LOG, "Starting elastic search on hosts: %s ", elasticSearchHosts.toString());
This log message seems odd.. It's not really "Starting" ES, but more "Connecting" to ES on these hosts isn't it?

2020-10-30 05:35 UTC, tallpsmith commented on src/test/java/com/aconex/scrutineer/CompositeStreamVerifierListenerTest.java
> +    public void testShouldDelegateToAllListenersOnPrimaryStreamProcessed() {
This is more a style comment, but given each test method is annotated with the `@Test` marker, I prefer to remove the prefix `test` from each method for readability.    I think it reads nicer.

2020-10-30 06:47 UTC, rock-yu commented on src/main/java/com/aconex/scrutineer/CmdLineOptionsSSLVerificationModeValidator.java
> +            throw new ParameterException("SSL verification mode can be one of: " + Arrays.toString(sslVerificationModes));
👍 Fixed in code

2020-10-30 06:57 UTC, rock-yu commented on src/main/java/com/aconex/scrutineer/ScrutineerCommandLineOptions.java
> +            description = "Transport client SSL verification mode, accepted values: [none, certificate, full]", validateValueWith = CmdLineOptionsSSLVerificationModeValidator.class)
I've added new Jcommander parameter "--help or -h" to print out the usage. 

Yes, JCommander will printout which is the default:



```
 ./target/appassembler/bin/scrutineer -h
Usage: <main class> [options]
  Options:
  * --clusterName
      ElasticSearch cluster name identifier
  * --esHosts
      CSV set of seed ElasticSearch host:port pairs to use as part of 
      discovery 
    --esPassword
      Elasticsearch Password
    --esSSLEnabled
      Enable SSL encryption for transport client
      Default: false
    --esSSLVerificationMode
      Transport client SSL verification mode, accepted values: [none, 
      certificate, full]
      Default: certificate

```

2020-10-30 06:59 UTC, rock-yu commented on src/main/java/com/aconex/scrutineer/elasticsearch/ElasticSearchTransportClientFactory.java
> +        LogUtils.debug(LOG, "Starting elastic search on hosts: %s ", elasticSearchHosts.toString());
Good point, fixed in code

2020-10-30 06:59 UTC, rock-yu commented on src/test/java/com/aconex/scrutineer/CompositeStreamVerifierListenerTest.java
> +    public void testShouldDelegateToAllListenersOnPrimaryStreamProcessed() {
It was a mistake to add `test` prefix. Fixed in code

2020-11-05 05:56 UTC, tallpsmith commented on src/main/java/com/aconex/scrutineer/elasticsearch/ElasticSearchTransportClientFactory.java
> +        LogUtils.debug(LOG, "Connecting to elastic search on hosts: %s ", elasticSearchHosts.toString());
`pedanticMode: On`

Can you make that string `Elasticsearch`... ? :-D

2020-11-05 05:57 UTC, tallpsmith requested changes
Minor string fixup and we're done!

2020-11-05 06:08 UTC, rock-yu commented on src/main/java/com/aconex/scrutineer/elasticsearch/ElasticSearchTransportClientFactory.java
> +        LogUtils.debug(LOG, "Connecting to elastic search on hosts: %s ", elasticSearchHosts.toString());
Sure, I've renamed "elastic search" to "Elasticsearch"

2020-11-05 06:15 UTC, tallpsmith approved these changes

2020-11-05 06:16 UTC, merged