Modularize scrutineer
Aconex/scrutineer pull request #52
Opened 2021-07-30 07:04 UTC by rock-yu

## Proposed changes

Modularized scrutineer into core/elasticsearch7/jdbc/scrutineer(runner) modules so that we can:
1) extend the Stream implementations and pick and compose what we need
2) depend only on the Verifier module with in-house Stream implementations
3) maintain the existing capability to run rpm or install tarball through scrutineer(runner) module
4) existing clients who depend on "com.aconex.scrutineer:scrutineer" will continue to work 

**This addresses issue #x**

## Checklist

- [ x] I've read the [CONTRIBUTING](https://github.com/Aconex/scrutineer/blob/master/CONTRIBUTING.md) doc
- [x ] All tests pass locally with my changes
- [ ] I've added unit tests and integration tests.
- [ ] I've added necessary documentation (if appropriate)

## Further comments

2021-08-01 23:56 UTC, tallpsmith commented
I'm just trying to work out why Travis hasn't tried to build this MR....

2021-08-02 23:40 UTC, tallpsmith requested changes
Can you have a look at the feedback here (fairly minor).

I wish there was a way for the import order to be consistent - we probably need to define what they should be for this Project to avoid 'diff noise'.

2021-08-02 23:41 UTC, tallpsmith commented on elasticsearch7/src/test/resources/pmd.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I think you addressed this in the latest commit, but just check and resolve if you feel it already did.

2021-08-02 23:43 UTC, tallpsmith commented
Last points for discussion is about version numbering and CHANGELOG.  If you can update the version SNAPSHOT to indicate a "major" (though not necessarily breaking) change?  I think the CHANGELOG should outline what was done too if you can add something there please.

2021-08-03 05:57 UTC, rock-yu commented on core/src/main/java/com/aconex/scrutineer/javautil/ControlledTimeSource.java
> +public class ControlledTimeSource implements TimeSource {
Done

2021-08-03 05:57 UTC, rock-yu commented on jdbc/src/test/java/com/aconex/scrutineer/jdbc/JdbcIdAndVersionStreamTest.java
> +        Mockito.when(connection.createStatement()).thenReturn(statement);
Done

2021-08-03 06:05 UTC, rock-yu commented on elasticsearch7/src/test/java/com/aconex/scrutineer/elasticsearch/IdAndVersionDataReaderTest.java
> +        MatcherAssert.assertThat(idAndVersion.getId(), is(ID));
Done

2021-08-03 06:05 UTC, rock-yu commented on elasticsearch7/src/test/java/com/aconex/scrutineer/elasticsearch/IdAndVersionInputStreamIteratorTest.java
> +        assertThat(idAndVersionInputStreamIterator.next(), CoreMatchers.is(idAndVersion));
Done

2021-08-03 06:05 UTC, rock-yu commented on elasticsearch7/src/test/java/com/aconex/scrutineer/elasticsearch/IdAndVersionInputStreamIteratorTest.java
> +        assertThat(idAndVersionInputStreamIterator.next(), CoreMatchers.is(idAndVersion));
Done

2021-08-03 06:06 UTC, rock-yu commented on elasticsearch7/src/test/resources/pmd.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Done

2021-08-03 06:11 UTC, tallpsmith commented on jdbc/src/test/java/com/aconex/scrutineer/jdbc/JdbcIdAndVersionStreamTest.java
> +        assertThat(iterator.getResultSet(), Is.is(resultSet));
this doesn't look like it's statically imported ?

2021-08-03 06:11 UTC, tallpsmith commented on jdbc/src/test/java/com/aconex/scrutineer/jdbc/JdbcIdAndVersionStreamTest.java
> +            Assert.fail("Unexpected exception");
no static import?

2021-08-03 06:20 UTC, rock-yu commented on elasticsearch7/pom.xml
> +            <artifactId>x-pack-transport</artifactId>
It was existing dependencies we added before. Still I checked, the x-pack security is free and open-sourced, https://www.elastic.co/blog/security-for-elasticsearch-is-now-free
https://www.elastic.co/blog/doubling-down-on-open

2021-08-03 06:23 UTC, rock-yu commented on core/src/main/java/com/aconex/scrutineer/javautil/ControlledTimeSource.java
> +public class ControlledTimeSource implements TimeSource {
Done, moved to Test

2021-08-03 06:26 UTC, tallpsmith commented on elasticsearch7/pom.xml
> +            <artifactId>x-pack-transport</artifactId>
free does not imply "good license"....

2021-08-03 06:28 UTC, tallpsmith commented on elasticsearch7/pom.xml
> +            <artifactId>x-pack-transport</artifactId>
I'll create a seperate issue for that.

2021-08-03 06:32 UTC, rock-yu commented on scrutineer/pom.xml
> +        <dependency>
This pom is actually no longer the top-level. This sub-module (stilled called scrutineer) represents the Command line runner, it runs the default JDBC against ES, so it requires all these dependencies.

2021-08-03 07:22 UTC, rock-yu commented
> Last points for discussion is about version numbering and CHANGELOG. If you can update the version SNAPSHOT to indicate a "major" (though not necessarily breaking) change? I think the CHANGELOG should outline what was done too if you can add something there please.

2021-08-03 07:25 UTC, merged