57 flexible configuration
Aconex/scrutineer pull request #59
Opened 2021-08-04 11:35 UTC by rock-yu

## Proposed changes

Implemented "scrutineer2" to run verification with a pair of stream configurations (existing bin/scrutineer is still supported)
```
scrutineer/target/appassembler/bin/scrutineer2 \
    --primary-config=jdbc.properties \
    --secondary-config=elasticsearch7.properties \
    --numeric
```

**This addresses issue #57 **

## Checklist

- [ x] I've read the [CONTRIBUTING](https://github.com/Aconex/scrutineer/blob/master/CONTRIBUTING.md) doc
- [x ] All tests pass locally with my changes
- [x] I've added unit tests and integration tests.
- [ ] I've added necessary documentation (if appropriate)

## Further comments
Let's start the review/discussion first, I will amend the README, CHANGELOG in separate commits

2021-08-05 01:22 UTC, tallpsmith reviewed
Can you pull out the `TODOs` into issues and remove from the code?

2021-08-05 01:22 UTC, tallpsmith commented on scrutineer/src/main/java/com/aconex/scrutineer/v2/ScrutineerCommandLineOptionsV2Extension.java
> +            return new HashMap(properties);
Should we consider making this an immutable Map?

2021-08-05 01:22 UTC, tallpsmith commented
Also if you can rebase as I've added security checks to the Github workflows set that you can bring in.

2021-08-05 01:51 UTC, rock-yu commented on scrutineer/config/elasticsearch7.properties
> +stream.connector.class=com.aconex.scrutineer.elasticsearch.v7.ElasticSearchStreamConnector
Yes they are. Same way kafka-connector ship their configurations. https://github.com/confluentinc/kafka-connect-jdbc/tree/master/config

2021-08-05 01:53 UTC, rock-yu commented on scrutineer/config/elasticsearch7.properties
> +stream.connector.class=com.aconex.scrutineer.elasticsearch.v7.ElasticSearchStreamConnector
I think we should add separate documentation for each field we support

2021-08-05 01:53 UTC, rock-yu commented on scrutineer/src/main/java/com/aconex/scrutineer/v2/ScrutineerCommandLineOptionsV2Extension.java
> +            return new HashMap(properties);
Good point, will do

2021-08-05 05:40 UTC, rock-yu commented on scrutineer/config/elasticsearch7.properties
> +stream.connector.class=com.aconex.scrutineer.elasticsearch.v7.ElasticSearchStreamConnector
I've rename them to _example-elasticsearch7.properties_ and _example-jdbc.properties_ so user won't need to second guess them

2021-08-05 07:14 UTC, tallpsmith commented on scrutineer/config/elasticsearch7.properties
> +stream.connector.class=com.aconex.scrutineer.elasticsearch.v7.ElasticSearchStreamConnector
yeah that's a much better idea, thanks.

2021-08-05 08:46 UTC, rock-yu commented
I have updated README AND CHANGELOG with instructions to run scrutineer2

2021-08-05 22:45 UTC, tallpsmith requested changes
Looking great, just a tiny set of changes and we're done.

2021-08-05 22:45 UTC, tallpsmith commented on README.md
> +Provide `conf/jdbc.properties` to create the primary stream
Probably worth mentioning here that the primary & secondary streams can be ANY type of configuration, not just the example here (though this is the common pattern).

2021-08-05 22:45 UTC, tallpsmith commented on README.md
> +* **stream.connector.class** – The connector class to use to create the stream
Can you create a local URL reference to the 2 example configuration files that outline ALL the config options in the README?  For example, doesn't the ES one have Authentication support already?  Just want to link the documentation.

2021-08-05 22:45 UTC, tallpsmith commented on scrutineer/src/main/java/com/aconex/scrutineer/v2/ScrutineerCommandLineOptionsV2Extension.java
> +        try (InputStream is = this.getClass().getClassLoader().getResourceAsStream(configProperty)) {
ok so this is _requiring_ that the config file be part of the class path?  We should document that requirement in the `README` (it wasn't clear what the relative reference is in the docs there)

2021-08-06 00:06 UTC, rock-yu commented on README.md
> +Provide `conf/jdbc.properties` to create the primary stream
Good point

2021-08-06 00:08 UTC, rock-yu commented on README.md
> +* **stream.connector.class** – The connector class to use to create the stream
DONE, user can click the link to see the full list of configuration and definitions for each field (the README is a lot less noisy now)

2021-08-06 00:10 UTC, rock-yu commented on scrutineer/src/main/java/com/aconex/scrutineer/v2/ScrutineerCommandLineOptionsV2Extension.java
> +        try (InputStream is = this.getClass().getClassLoader().getResourceAsStream(configProperty)) {
Yes, `config` was added to the classpath.

I've updated the README: 

* **primary-config** - the configuration file for the primary stream, placed under `config` folder

2021-08-06 03:27 UTC, tallpsmith approved these changes

2021-08-06 03:35 UTC, merged